version: "3"

services:
  php:
    container_name: php-${APP_NAME}
    restart: always
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
      args:
        - TIMEZONE=${PHP_FPM_TIMEZONE}
        - INSTALL_GD=${PHP_FPM_INSTALL_GD}
        - INSTALL_COMPRESSION=${PHP_FPM_INSTALL_COMPRESSION}
        - INSTALL_FTP=${PHP_FPM_INSTALL_FTP}
        - INSTALL_MBSTRING=${PHP_FPM_INSTALL_MBSTRING}
        - INSTALL_PDO_MYSQL=${PHP_FPM_INSTALL_PDO_MYSQL}
        - INSTALL_PDO_POSTGRESQL=${PHP_FPM_INSTALL_PDO_POSTGRESQL}
        - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
        - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
        - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
        - INSTALL_APCU=${PHP_FPM_INSTALL_APCU}
        - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
        - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
        - INSTALL_TOKENIZER=${PHP_FPM_INSTALL_TOKENIZER}
        - INSTALL_JSON_XML=${PHP_FPM_INSTALL_JSON_XML}
        - INSTALL_CURL=${PHP_FPM_INSTALL_CURL}
        - INSTALL_OPENSSL=${PHP_FPM_INSTALL_OPENSSL}
        - INSTALL_COMPOSER=${PHP_FPM_INSTALL_COMPOSER}
        - INSTALL_AMQP=${PHP_FPM_INSTALL_AMQP}
        - INSTALL_REDIS=${PHP_FPM_INSTALL_REDIS}
    volumes:
      - ${APPLICATION}:/var/www/html
    networks:
      - network-service-api
  redis:
    image: redis:latest
    container_name: redis-${APP_NAME}
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./docker/redis/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    networks:
      - network-service-api
  nginx:
    container_name: nginx-${APP_NAME}
    restart: always
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - "${APPLICATION}:/var/www/html"
      - "/var/log/${APP_NAME}:/var/log/nginx"
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    networks:
      - network-service-api
    depends_on:
      - php
networks:
  network-service-api:
    driver: bridge